
services:

  backend:
    build:
      context: ./backend_files
      dockerfile: Dockerfile

    container_name: pneumonia-backend

    environment:
      HF_TOKEN: ${HF_TOKEN:-}
      MODEL_REPO_ID: ${MODEL_REPO_ID:-Chandrashekhara/pneumonia_prediction_model}
      MODEL_FILENAME: ${MODEL_FILENAME:-pneumonia_prediction_model_MobileNetV2_ffnn.keras}

    ports:
      - "7860:7860"

    restart: unless-stopped


  frontend:
      build:
        context: ./frontend_files
        dockerfile: Dockerfile
      container_name: pneumonia-frontend
      environment:
        BACKEND_URL: http://backend:7860
        HF_TOKEN: ${HF_TOKEN:-}
      depends_on:
        backend:
          condition: service_healthy
      ports:
        - "8501:7860"   # Maps http://localhost:8501 -> container:7860
      restart: unless-stopped
